splash_texts = [
  "skill issue",
  "%input-free!",
  "%input issue x%jn",
  "hi",
  "ONG FR FR",
  "\"muckers\"",
  "Pro Tip: You can use the console to edit stuff",
  "%h",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",

  
];
famous_peoples = [
  "This game",
  "This website",
  "That other website",
  "Youtube",
  "The average Frenchman",
  "The French language",
  "Tqnixity",
  "Tqnixity's girlfriend",
  "Tqnixity the one and only",
  "Jimmy Kimmel",
  "Ron Kolbus",
  "Tqnixity's nonexistent cat",
  "Dogmeat Ltd.",
  "Dream",
  "Technoblade",
  "Technoblade (never dies!)",
  "the gubbmint",
  "Anonymous",
  "Donald Trump",
  "Steve Jobs",
  "Karl Marx",
  "w3schools",
  "Diddy",
  "Sean \"Diddy\" Combs",
  "Jeffrey Epstein",
  "David Baszucki",
  "Jackie Chan",
  "John Xing",
  "John Cena",
  "Xi Jinping",
  "Winnie the Pooh",
  "Peppa Pig",
  "Greg George",
  "Hiroshima Nagasaki",
  "ohman",
  "Tqnixity's piano",
  "Tqnixity's 15th piano",
  "Martin Luther King",
  "generic feminist",
  "Local neighbourhood Karen",
  "Greg Washington",
  "ghDhaeighnyieaieieighaelle Kqghaeioughieie",
  "Jimmy \"MrBeast\" Donaldson",
  "Indian Times",
  "South China News",
  "CCTV Channel 15",
  "Vladimir Putin",
  "Susan Wojcikizkkjzcki",
  "New York Times",
  "MOJANG",
  "The Verge",
  "CBC",
  "Alien #7531 from Mars",
  "Albert Einstein",
  "Socrates",
  "Plato",
  "Queen Elizabeth II",
  "[person here]",
  "Yamete Wokudasai",
  "Mao Zedong",
  "Adolf Charles (1556)",
  "John Stevenson",
  "Kate Dickens",
  "Bob Smith",
  "Schrodinger",
  "Hangtian Rijie",
  "Jaewa Park",
  "Sum Ting Wong",
  "Bang Ding Ow",
  "James Charles",
  "Buster Chaplin",
  "Loser Lane",
  "Youckeugh",
  "Jyioughckaeouhgh Yuca",
  "Streetsville Mass Shooter",
  "Henry Henry",
  "Dickens Dickens",
  "the number 25",
  "Ender Dragon",
  "Piglin Brute",
  "Villager News",
  "Villager #9",
  "Pillager",
  "Johnny Appleseed",
  "Happy Ghast",
  "George Orwell's book",
  "The average adult male",
  "The average adult female",
  "The average person",
  "The average child",
  "The average house",
  "The average car",
  "The average nerd",
  "The average autistic person",
  "The average quadriplegic",
  "The average NERDDDDDD",
  "Minecraft's tier ranking system",
  "The concept of Kansas",
  "Tqnixity's medical record",
  "The average desk",
  "The average smartphone",
  "My pet T-Rex",
  "Everyone",
  "Nobody",
  "Darkness",
  "THE LIGHT",
  "The 4 elements",
  "Life's biggest question",
  "He asked if it",
  "Pro Tip: it",
  "Pro Tip: this",
  "Pro Tip: Tqnixity",
  "Pro Tip",
  "Greta Thunberg",
  "The local Titanoboa",
  "My pet clanker",
  "Clankers",
  "ChatGPT",
  "The meaning of life",
  "The local HOA",
  "The local Titanoboa",
  "My pet Ender Dragon",
  "My pet Happy Ghast",
  "Obesity",
  "All humor ",
  "The number 69",
  "Babies",
  "The average anaconda",
  "The average blue whale",
  "The average elephant",
  "Klarna",
  "W3spaces",
  "GitHub",
  "The windows command prompt",
  "The concept of time",
  "Tqnixity's calculator addiction",
  "Japan Airlines flight 123",
]
dhaub_initial = [
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "We are",
  "They are",
  "You are",
  "Your name is:",
  "%t: ",
  "%t is",
  "%t is not",
  "%t: ",
  "%t is",
  "%t is not",
  "%t: ",
  "%t is",
  "%t is not",
  "%input is",
  "%input is not",
  "%input: ",
  "Tqnixity is",
  "Tqnixity is not",
  "This website is",
  "Tqnixity is",
  "Tqnixity is not",
  "This website is",
  "Tqnixity is",
  "This website is",
  "Tqnixity is addicted to being",
  "Tqnixity is addicted to being",
  "Tqnixity's nonexistent cat is",
  "Tqnixity's rank is",
  "OMEN is",
  "It's",
  "Tqnixity's friends are",
  "Tqnixity's osu! profile is",
  "早上好，现在我有",
  "Employee password:",
  "Credit card number:",
  "This video is",
  "This car is",
  "My mouse is",
  "2012:",
  "1996:",
  "2020:",
  "1942:",
  "1885:",
  "1669:",
  "2055:",
  "Mission Impossible:",
  "Garfield:",
  "Spider-Man:",
  "This oak tree is",
  "My pet t-rex is",
  "My pet megalodon is",
  "My pet titanoboa is",
  "My pet velociraptor is",
  "My pet neanderthal is",
  "Giant spiders: ",
  "I am",
  "Bitcoin wallet:",
  "Enter current time:",
  "Username:",
  "%f%'s dumbest moment was",
  "%f%'s dumbest moment was",
  "%f%'s life goal was",
  "%f%'s life goal was",
  "%f%'s greatest achievement was",
  "%f%'s greatest achievement was",
  "Expiration date:",
  "Tqnixity's brian is",
  "The average obese person is",
  "The average clanker is",
  "The average clanker is not",
  "Clankers:",
  "The Chinese:",
  "The average furry is",
  "The average alpha-male podcaster is",
  "Humor in the future:",
  "Bill Nye is",
  "Graham Cracker is",
  "My history teacher is",

];
dhaub_final = [
  "gonna make me miss my exit",
  "neal.fun",
  "a 1.5^{2}\ x+yy+zz\ 2^{2}\left\{0xyz\right\}",
  "a subscription service",
  "ding seoi",
  "reading a book",
  "booking a read",
  "busy",
  "busy with %input",
  "salivating for %input",
  "struggling with %input",
  "not finna pass this class",
  "rapping",
  "trapping",
  "$100,000 in debt and refusing to pay it off",
  "actively facilitating indentured servitude",
  "banned from onlyfans",
  "running an onlyfans",
  "multi-streaming (illegal!)",
  "being swallowed by a whale",
  "shooting threes",
  "playing ball with %input",
  "juggling",
  "secretly a russian spy",
  "getting busy with %input",
  "in a %input",
  "not in a %input",
  "fucking %input",
  "%input-less",
  "%inputful",
  "making %input",
  "in spain without the a",
  "censored",
  "banned",
  "shadowbanned by the algorithm",
  "an algorithm",
  "secretly an AI",
  "the harbinger of the Apocalypse",
  "a ticking time bomb",
  "a pot of gold",
  "collecting clankers",
  "playing osu!",
  "attempting to play the piano",
  "a CLANKER",
  "%input",
  "collecting watches",
  "an avid collector of dust",
  "going to marry their high school",
  "surrounded by friends",
  "worldwide",
  "globally applauded",
  "suicidal",
  "collecting calculators",
  "dead :)",
  "a clone of %f%",
  "a clone of Tqnixity",
  "gonna die in %d20 days",
  "in %input condition",
  "in critical condition",
  "%jn years old",
  "%jn meters tall",
  "%jn kilos h e a v y",
  "depressed",
  "dense",
  "borderline autistic",
  "playing %input on the piano",
  "successful",
  "successfully %input",
  "on drugs",
  "on %input",
  "doing exercise and drinking water",
  "eating healthy",
  "eating %input",
  "eating \"healthy\"",
  "in bronze 1",
  "systematically ruining their life",
  "ruining his sleep schedule",
  "a moron",
  "a %input",
  "%input",
  "THE GOAT",
  "eating sugar",
  "a %d20/20 coder",
  "having %d20/20 luck",
  "wanting you to try %featured",
  "a %input issue",
  "the personification of a skill issue",
  "in your walls",
  "under your floorboards",
  "literally the smartest thing alive",
  "smarter than Tqnixity himself",
  "seeing you on this website for the %vth time",
  "a 6'5 200lb jacked ripped taekwondo black belt",
  "finna go like uh move from w3 to %input",
  "basically nonbinary from his girl ahh build",
  "*clears throat* no further explanation required",
  "a list of random doohickeys over %jn months",
  "TV compatible",
  "Nintendo 64 compatible",
  "Smartwatch compatible",
  "New York Times Square Billboard compatible",
  "bad for only allowing 20 files :/",
  "a %featured",
  //"...一杯冰淇淋。我很喜欢冰淇淋，但是速度与激情九比冰淇淋我最喜欢。所以...现在是音乐时间。一，二，三，准备！",
  "%jn seconds long",
  "free!",
  "Grandmaster III",
  "RADIANT",
  "voting",
  "attempting to vote",
  "not able to vote yet",
  "collecting VP (Vote Points)",
  "mispeleing \"Vote\" as \"Vore\"",
  "on fentttt",
  "an ally of Xi Jinping",
  "a fucking animal",
  "RAWWWWWWWWWWWW",
  "so raw that I can still hear it telling bruv to fuck off",
  "being eaten alive",
  "a horror movie",
  "in a horror movie",
  "in the Nether",
  "beating the enderdragon sub-5",
  "in the Aether",
  "DISGUSTAING",
  "t r i g g e r e d",
  "w i d e j o y",
  "[ i n s e r t k e r n i n g j o k e h e r e ]",
  "setting a record on the pacer test",
  "running his first sub-7 mile, ever (which is really slow!)",
  "so slow that a chronic vaper could outrun bro",
  "slower than a computer from DELL",
  "[valorant reference blocker]",
  "faster than Sonic",
  "faster than light somehow",
  "above average speed",
  "the slowest kid in class",
  "autistically bad at sports",
  "autistically bad at everything",
  "autistically good at everything",
  "autistic",
  "possibly on drugs to be this bad",
  "straight up impossible",
  "NBA material",
  "WNBA material",
  "playing hockey",
  "playing poker",
  "gambling his life away",
  "using the Luigi cheatcode",
  "making bank from gambling",
  "spending 30 minutes anxiously thinking",
  "abandoned",
  "making investments, but really poorly",
  "IMAGE MATERIALLLLLL",
  "deaf",
  "blind",
  "tasteless",
  "deliciously awful",
  "more awful than not being able to graduate because of lunch debt",
  "in a love-hate relationship with %input",
  "typing these messages",
  "safe",
  "13 shillings and a bobcat in old money",
  "playing the waterphone",
  "violently ill",
  "cocooned in a giant alien lifeform",
  "a living halloween decoration",
  "wearing an omen costume for christmas",
  "spying on russia",
  "collecting lemonade",
  "overly obsessed with public transport",
  "an absolute loser to be around",
  "a new movie on the metric system",
  "unlearning %input",
  "in a very important meeting about [topic]",
  "cooking :fire:",
  "literally dead",
  "still alive",
  "lying about cake",
  "randomly generated",
  "grown in red gatorade",
  "listening to masculine whitegirl playlist",
  "playing ball",
  "playing hardball",
  "a choosing beggar on fb marketplace",
  "a facebook marketplace %input",
  "even more useless than %featured",
  "even more useful than %featured",
  "playing old school runescape",
  "illegally manufacturing fear and dread",
  "selling feet pics",
  "selling dick pics",
  "550 lines long",
  "as big as a john and a thinggamabobber",
  "[diddy namedrop]",
  "[metric system namedrop]",
  "providing therapy",
  "touch-blind",
  "in spectator mode",
  "a movie about sunshine and rainbows",
  "The scariest movie of [year]",
  "a movie adaptation of tqnixity",
  "so unreal it would be called bad writing",
  "uncontrollable",
  "good for only allowing 20 files",
  "better",
  "complaining that Silksong is too hard",
  "complaining that Silksong is too easy",
  "good at everything",
  "knows how to do everything but is bad at everything",
  "anything and everything",
  "selling so hard he's a billionaire now",

];
