splash_texts = [
  "skill issue",
  "%input-free!",
  "%input issue x%jn",
  "hi",
  "ONG FR FR",
  "\"muckers\"",
  "Pro Tip: You can use the console to edit stuff",
  "u%h",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
    "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  "%dhaub -%f%",
  
];
famous_peoples = [
  "This website",
  "Youtube",
  "The French language",
  "Tqnixity",
  "Tqnixity's girlfriend",
  "Tqnixity the one and only",
  "Jimmy Kimmel",
  "Ron Kolbus",
  "Tqnixity's nonexistent cat",
  "Dogmeat Ltd.",
  "Dream",
  "Technoblade",
  "Technoblade (never dies!)",
  "the gubbmint",
  "Anonymous",
  "Donald Trump",
  "Steve Jobs",
  "Sean \"Diddy\" Combs",
  "Jeffrey Epstein",
  "David Baszucki",
  "Jackie Chan",
  "John Xing",
  "John Cena",
  "Xi Jinping",
  "Winnie the Pooh",
  "Peppa Pig",
  "Greg George",
  "Hiroshima Nagasaki",
  "Oman",
  "Canada",
  "Germany",
  "America",
  "Brazil",
  "Mongolia",
  "Latvia",
  "Estonia",
  "The estonian military",
  "The concept of guns",
  "The concept of throwing",
  "Tqnixity's ukelele",
  "Wealth Land",
  "Inequality Land",
  "Equation Land",
  "Distribution Land",
  "Matrix Land",
  "Vector Land",
  "Tqnixity's piano",
  "Tqnixity's 15th piano",
  "Martin Luther King",
  "generic feminist",
  "Local neighbourhood Karen",
  "Greg Washington",
  "ghDhaeighnyieaieieighaelle Kqghaeioughieie",
  "Jimmy \"MrBeast\" Donaldson",
  "Indian Times",
  "South China News",
  "CCTV Channel 15",
  "Vladimir Putin",
  "Susan Wojcikizkkjzcki",
  "New York Times",
  "MOJANG",
  "The Verge",
  "CBC",
  "Alien #7531 from Mars",
  "Albert Einstein",
  "Socrates",
  "Plato",
  "Queen Elizabeth II",
  "[person here]",
  "Yamete Wokudasai",
  "Mao Zedong",
  "Adolf Charles (1556)",
  "John Stevenson",
  "Kate Dickens",
  "Bob Smith",
  "Schrodinger",
  "Hangtian Rijie",
  "Jaewa Park",
  "Sum Ting Wong",
  "Bang Ding Ow",
  "James Charles",
  "Buster Chaplin",
  "Loser Lane",
  "Wolfgang Amadeus Mozart",
  "The number 26",
  "Piglin Brute",
  "Villager News",
  "Villager #9",
  "Pillager #67",
  "Johnny Appleseed",
  "George Orwell's book",
  "The average adult male",
  "The average adult female",
  "The average person",
  "The average child",
  "The average house",
  "The average car",
  "The average nerd",
  "The average autistic person",
  "The average quadriplegic",
  "Tier list videos",
  "Tier lists",
  "Minecraft PVP's tier system",
  "The concept of Kansas",
  "Tqnixity's medical record",
  "The average desk",
  "Everyone",
  "Nobody",
  "Obesity",
  "The 4 elements",
  "Life's biggest question",
  "Pro Tip: it",
  "Pro Tip: this",
  "Greta Thunberg",
  "Vibe-coding platforms",
  "ChatGPT",
  "The meaning of life",
  "The local HOA",
  "My pet Ender Dragon",
  "My pet Happy Ghast",
  "The number %d20",
  "Babies",
  "Payday loan platforms",
  "W3Spaces",
  "GitHub",
  "The windows command prompt",
  "The concept of time",
  "Tqnixity's calculator addiction",
  "God",
  "V1 from ULTRAKILL",
  "Gabriel Ultrakill",
  "MINOS PRIME",
  "SISYPHUS PRIME",
  "Benjamin",
  "maurice",
  "[DATA REDACTED]",
  "The concept of education",
  "The concept of education in the United States",
  "The one before me",
  "The local orphanage",
  "Gordon Freeman",
  "Michael",
  "Lee King",
  "Jonathan",
  "The mindflayer in the corner of the tavern wearing a very bad human disguise",
  "Ben",
  "Graham",
  "My Minecraft Dungeons Roll Build"
]
dhaub_initial = [
  "%f% is",
  "%f%:",
  "%f% is",
  "%f%:",
  "%f% is",
  "%f%:",
  "%f% is",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "%f% is",
  "%f% is not",
  "%f%:",
  "We are",
  "They are",
  "You are",
  "Your name is:",
  "%t: ",
  "%t is",
  "%t is not",
  "%t: ",
  "%t is",
  "%t: ",
  "%t is",
  "%input is",
  "%input is not",
  "%input: ",
  "Tqnixity is",
  "This website is",
  "Tqnixity is",
  "Tqnixity is not",
  "This website is",
  "Tqnixity is",
  "This website is",
  "Tqnixity is addicted to ",
  "Tqnixity is addicted to ",
  "Tqnixity's rank is",
  "Tqnixity's values are",
  "HP OMEN laptops are",
  "It's",
  "Tqnixity's friends are",
  "Tqnixity's osu! profile is",
  "早上好，现在我有",
  "Employee password:",
  "Credit card number:",
  "This video is",
  "This car is",
  "My mouse is",
  "20%d20:",
  "1996:",
  "2020:",
  "1942:",
  "1885:",
  "1669:",
  "2026:",
  "Mission Impossible:",
  "Garfield:",
  "Spider-Man:",
  "This oak tree is",
  "I am",
  "Bitcoin wallet:",
  "Enter current time:",
  "Username:",
  "%f%'s dumbest moment was",
  "%f%'s dumbest moment was",
  "%f%'s life goal was",
  "%f%'s life goal was",
  "%f%'s greatest achievement was",
  "%f%'s greatest achievement was",
  "Tqnixity's brian is",
  "The average obese person is",
  "The average clanker is",
  "The average clanker is not",
  "Clankers:",
  "Humor in the future:",
  "Bill Nye is",
  "My history teacher is",
  "THIS TICKET:",
  "%f%\'s punishment is",
];
dhaub_final = [
  "gonna make me miss my exit",
  "neal.fun",
  "a subscription service",
  "reading a book",
  "booking a read",
  "busy with %input",
  "salivating for %input",
  "struggling with %input",
  "not finna pass this class",
  "rapping",
  "trapping",
  "$100,000 in debt and refusing to pay it off",
  "facilitating indentured servitude",
  "running an onlyfans",
  "multi-streaming (illegal!)",
  "being swallowed by a whale",
  "shooting threes",
  "playing ball with %input",
  "juggling",
  "juggling 2: electric boogaloo",
  "secretly a russian spy",
  "getting busy with %input",
  "in a %input",
  "not in a %input",
  "fucking %input",
  "%input-less",
  "%inputful",
  "making %input",
  "in spain without the a",
  "censored",
  "banned",
  "shadowbanned by the algorithm",
  "an algorithm",
  "secretly an AI",
  "the harbinger of the Apocalypse",
  "a ticking time bomb",
  "a pot of gold",
  "playing osu!",
  "playing the harpsichord",
  "speedrunning the entire music conservatory",
  "a CLANKER",
  "%input",
  "collecting watches",
  "an avid collector of dust",
  "going to marry their high school",
  "surrounded by friends",
  "worldwide",
  "being sent more life in lieu of flowers",
  "globally applauded",
  "suicidal",
  "collecting calculators",
  "dead :)",
  "a clone of %f%",
  "a clone of Tqnixity",
  "gonna die in %d20 days",
  "in %input condition",
  "in critical condition",
  "%jn years old",
  "%jn meters tall",
  "%jn kilos h e a v y",
  "depressed",
  "dense",
  "death",
  "borderline autistic",
  "playing %input on the piano",
  "successful",
  "successfully %input",
  "on drugs",
  "on %input",
  "doing exercise and drinking water",
  "eating healthy",
  "eating %input",
  "eating \"healthy\"",
  "in bronze 1",
  "systematically ruining their life",
  "ruining his sleep schedule",
  "a moron",
  "a %input",
  "%input",
  "THE GOAT",
  "having %d20/20 luck",
  "wanting you to try %featured",
  "a %input issue",
  "the personification of a skill issue",
  "in your walls",
  "under your floorboards",
  "literally the smartest thing alive",
  "seeing you on this website for the %vth time",
  "a 6'5 200lb jacked ripped taekwondo black belt",
  "*clears throat* no further explanation required",
  "considering buying a domain for this website",
  "a list of random doohickeys over %jn months",
  "TV compatible",
  "Nintendo 64 compatible",
  "smartwatch compatible",
  "New York Times Square Billboard compatible",
  "bad for only allowing 20 files :/",
  "a %featured",
  //"...一杯冰淇淋。我很喜欢冰淇淋，但是速度与激情九比冰淇淋我最喜欢。所以...现在是音乐时间。一，二，三，准备！",
  "%jn seconds long",
  "not able to drive yet",
  "not able to vote yet",
  "collecting VP",
  "mispeleing \"Vote\" as \"Vore\"",
  "on fent",
  "an ally of Xi Jinping",
  "a fucking animal",
  "RAWWWWWWWWWWWW",
  "so raw that I can still hear it saying to fuck off",
  "a horror movie",
  "in a horror movie",
  "beating the enderdragon sub-5",
  "in the Aether",
  "DISGUSTAING",
  "T R I G G E R E D",
  "+ENRAGED",
  "setting a world record on the pacer test",
  "running his first sub-7 mile, ever",
  "slower than a chronic vaper",
  "slower than a computer from DELL",
  "[valorant reference blocker]",
  "[ULTRAKILL fandom reference blocker]",
  "faster than Sonic",
  "above average speed",
  "the slowest kid in class",
  "autistically bad at sports",
  "autistically bad at everything",
  "autistically good at everything",
  "autistic",
  "def on drugs to be this bad",
  "straight up impossible",
  "NBA material",
  "WNBA material",
  "playing hockey",
  "playing poker",
  "gambling his life away",
  "using the Luigi cheatcode",
  "making bank from gambling",
  "spending 30 minutes anxiously thinking about gambling",
  "abandoned",
  "making investments, but really poorly",
  "IMAGE MATERIAL",
  "deaf",
  "blind",
  "tasteless",
  "deliciously awful",
  "more awful than not being able to graduate because of lunch debt",
  "in a love-hate relationship with %input",
  "typing these messages",
  "safe",
  "not safe",
  "13 shillings and a bobcat in old money",
  "playing the waterphone",
  "violently ill",
  "cocooned in %v layers of blankets",
  "a living halloween decoration",
  "wearing an omen costume for christmas",
  "spying on russia",
  "collecting lemonade",
  "overly obsessed with public transport",
  "unable to comprehend the concent of %input",
  "an absolute loser to be around",
  "a new movie on the metric system",
  "in a very important meeting about %input",
  "cooking :fire:",
  "DEAD. GONE. REDUCED TO NOTHING.",
  "\"RECONSTRUCT WHAT? THERES NOTHING LEFT!\" -Hakita Ultrakill",
  "lying about cake",
  "randomly generated",
  "grown in red gatorade",
  "playing ball",
  "playing hardball",
  "a facebook marketplace %input",
  "even more useless than %featured",
  "even more useful than %featured",
  "playing old school runescape",
  "illegally manufacturing fear and dread",
  "selling feet pics",
  "550 lines long",
  "as big as a john and a thinggamabobber",
  "[diddy namedrop]",
  "[metric system namedrop]",
  "providing therapy",
  "in spectator mode",
  "a movie about sunshine and rainbows",
  "The scariest movie of [year]",
  "a movie adaptation of tqnixity",
  "on tylenol",
  "so unreal it would be deemed as bad writing",
  "uncontrollable",
  "controlled",
  "precise",
  "accurate",
  "the demoman",
  "the ULTRAKILL(tm)",
  "currently heading towards your location at Mach 7",
  "setting up %input",
  "projectile boosting a maurice with the knuckleblaster",
  "+MAURICED",
  "+FISTFUL OF DOLLAR",
  "+ULTRACOUNTERRICOSHOT x67108863",
  "dead. Blood is fuel. Hell is full.",
  "+SCRINDONGULODED",
  "trying to BLJ into a parallel universe",
  "good for only allowing 20 files",
  "better",
  "complaining that Silksong is too hard",
  "complaining that Silksong is too easy",
  "good at everything",
  "knows how to do everything but is bad at everything",
  "selling so hard he's a billionaire now",
"strong",
  "strong-willed",
  "determined",
  "hardworking",
  "creative and inventive",
  "loved by many",
  "smart",
  "good, %f% is great",
  "love, %f% is life",
  "currently on a mass murder spree for RAM",
  "committing genocide for AI data centres",
  "an absolute fucking girlboss",
  "being replaced by AI",
  "leaking my SSN",
  "creaking",
  "a slave to society",
  "a society of slaves",
  "responsible",
  "knowledgeable",
  "disciplined",
  "reliable",
  "kind and passionate",
  "hardworking",
  "grateful",
  "imperfect, but so is everyone else",
  "courageous",
  "brave",
  "valuable",
  "priceless to others",
  "important to friends and family",
  "easily gender-reassignable",
  "[DATA REDACTED]",
  "considering redesigning this website",
  "good for %input",
  "an obsolete %f%",
  "speedrunning life",
  "a man of few words",
  "replacing AI",
  "OH GOD ITS SELF REPLICATING",
  "literally as generic as it can get",
  "vibe-coded",
  "powerful",
  "versatile",
  "functionally illiterate",
  "powered by self-resentment",
  "powered by shame",
  "powered by Unity",
  "powered by hopes, dreams, and prayers",
  "reducing educational opportunities for poors",
  "against the existence of mentally abled people",
  "in desperate need of reform",
  "line 449",
];
